-- AlterEnum
ALTER TYPE "IdempotencyScope" ADD VALUE IF NOT EXISTS 'SESSION';
ALTER TYPE "IdempotencyScope" ADD VALUE IF NOT EXISTS 'KITCHEN';
ALTER TYPE "IdempotencyScope" ADD VALUE IF NOT EXISTS 'MUTATION';
