/** Plain-language labels for activity CSV / exports. */
const ACTIVITY_LABELS: Record<string, string> = {
  'auth.approval_pin': 'Manager approval used',
  'auth.approval_pin_failed': 'Manager approval failed',
  'auth.change_password': 'Password changed',
  'auth.change_pin': 'PIN changed',
  'auth.lock': 'Screen locked',
  'auth.logout': 'Logged out',
  'auth.password_login': 'Signed in with password',
  'auth.password_login_failed': 'Password sign-in failed',
  'auth.pin_login': 'Signed in with PIN',
  'auth.pin_login_failed': 'PIN sign-in failed',
  'auth.revoke_sessions': 'Signed out of all devices',
  'employee.archive': 'Employee removed',
  'employee.create': 'Employee added',
  'employee.deactivate': 'Employee deactivated',
  'employee.reactivate': 'Employee reactivated',
  'employee.update': 'Employee updated',
  'guest.join': 'Guest joined a table',
  'inventory.archive': 'Stock item archived',
  'inventory.count': 'Stock counted',
  'inventory.create': 'Stock item added',
  'inventory.receive': 'Stock received',
  'inventory.update': 'Stock item updated',
  'inventory.waste': 'Waste recorded',
  'inventory.staff_meal': 'Staff meal recorded',
  'inventory.spoilage': 'Spoilage recorded',
  'inventory.stock_return': 'Stock returned to supplier',
  'inventory.adjustment': 'Stock adjusted',
  'inventory.purchase_receipt': 'Delivery received',
  'inventory.production_input': 'Used in prep',
  'inventory.production_output': 'Made in prep',
  'inventory.sale_consumption': 'Used for guest order',
  'inventory.opening_stock': 'Opening stock set',
  'menu.category.archive': 'Menu category archived',
  'menu.category.create': 'Menu category added',
  'menu.category.update': 'Menu category updated',
  'menu.item.archive': 'Dish removed from menu',
  'menu.item.create': 'Dish added',
  'menu.item.update': 'Dish updated',
  'menu.modifier_group.archive': 'Modifier group archived',
  'menu.modifier_group.create': 'Modifier group added',
  'menu.modifier_group.update': 'Modifier group updated',
  'menu.modifier_option.archive': 'Modifier option archived',
  'menu.modifier_option.create': 'Modifier option added',
  'menu.modifier_option.update': 'Modifier option updated',
  'menu.special.create': 'Special created',
  'menu.special.deactivate': 'Special cleared',
  'menu.special.update': 'Special updated',
  'order_item.cancelled': 'Order item cancelled',
  'order_item.remake': 'Order item remake',
  'order_item.remake_requested': 'Remake requested',
  'order_item.remake_declined': 'Remake declined',
  'order_item.transition': 'Kitchen status changed',
  'order_item.unavailable': 'Item marked unavailable',
  'order.reopened': 'Paid order reopened',
  'order.sent_to_kitchen': 'Order sent to kitchen',
  'payment.correct_method': 'Payment method corrected',
  'payment.receipt_reprint': 'Receipt reprinted',
  'payment.refund': 'Refund issued',
  'payment.settle': 'Bill settled',
  'payroll.create': 'Payroll record created',
  'payroll.mark_paid': 'Salary marked paid',
  'production.confirm_batch': 'Production batch confirmed',
  'recipe.create': 'Recipe created',
  'recipe.deactivate': 'Recipe deactivated',
  'recipe.update': 'Recipe updated',
  'retention.guest_display_name_anonymize': 'Guest names cleared (privacy)',
  'session.close': 'Table closed',
  'session.guest.add': 'Guest added to table',
  'session.move': 'Table moved',
  'session.open': 'Table opened',
  'session.waiter_accepted': 'Waiter accepted table call',
  'session.waiter_assigned': 'Waiter assigned to table',
  'shift.apply_template': 'Shift template applied',
  'shift.assign': 'Shift assigned',
  'shift.copy_week': 'Shifts copied from last week',
  'shift.remove': 'Shift removed',
  'supplier.create': 'Supplier added',
  'supplier.update': 'Supplier updated',
  'table.archive': 'Table archived',
  'table.cleaning_complete': 'Table marked clean',
  'table.create': 'Table added',
  'table.qr.deactivate': 'Table QR deactivated',
  'table.qr.rotate': 'Table QR rotated',
  'table.status': 'Table status changed',
  'table.update': 'Table updated',
  'till.adjustment_approved': 'Till adjustment approved',
  'till.close': 'Till closed',
  'till.open': 'Till opened',
};

function titleCaseDots(code: string) {
  return code
    .replace(/[._]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

export function humanizeActivityAction(actionType: string): string {
  return ACTIVITY_LABELS[actionType] ?? titleCaseDots(actionType);
}

const MOVEMENT_LABELS: Record<string, string> = {
  purchase_receipt: 'Delivery received',
  production_input: 'Used in prep',
  production_output: 'Made in prep',
  sale_consumption: 'Used for guest order',
  waste: 'Waste',
  staff_meal: 'Staff meal',
  spoilage: 'Spoilage',
  adjustment: 'Stock count adjustment',
  stock_return: 'Returned to supplier',
  opening_stock: 'Opening stock',
};

export function humanizeMovementType(type: string): string {
  return MOVEMENT_LABELS[type] ?? titleCaseDots(type);
}
